version: '3'
services:
    web:
        build:
            context: .
            dockerfile: .docker/nginx/Dockerfile
        volumes:
            - ./public:/var/www/forum/public:cached
        ports:
            - "8080:80"
        links:
            - app
        container_name: forum_webserver
    app:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
            args:
              INSTALL_XDEBUG: ${INSTALL_XDEBUG_ENV}
              INSTALL_COMPOSER: ${INSTALL_COMPOSER_ENV}
              INSTALL_NODE: ${INSTALL_NODE_ENV}
              INSTALL_GIT: ${INSTALL_GIT_ENV}
              INSTALL_PHPMD: ${INSTALL_PHPMD_ENV}
              INSTALL_PHPCS: ${INSTALL_PHPCS_ENV}
        volumes:
            - ./:/var/www/forum:cached
            - .docker/php/zz-xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - .docker/php/zz-php.ini:/usr/local/etc/php/php.ini
        links:
            - database
        environment:
            - "MAIL_DRIVER=${MAIL_DRIVER_ENV}"
            - "MAIL_HOST=${MAIL_HOST_ENV}"
            - "MAIL_PORT=${MAIL_PORT_ENV}"
            - "FROM_ADDRESS=${FROM_ADDRESS_ENV}"
            - "FROM_NAME=${FROM_NAME_ENV}"
            - "MAIL_ENCRYPTION=${MAIL_ENCRYPTION_ENV}"
            - "MAIL_USERNAME=${MAIL_USERNAME_ENV}"
            - "MAIL_PASSWORD=${MAIL_PASSWORD_ENV}"
        container_name: forum_app
    database:
        image: mysql:5.7.21
        volumes:
            - forum_data:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD_ENV}"
            - "MYSQL_DATABASE=${DATABASE_NAME_ENV}"
        ports:
            - "33060:3306"
        container_name: forum_database
volumes:
    forum_data:
